In [14]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [15]:
df=pd.read_csv(r"C:\Users\HP\Desktop\Bacancy\AI_ML\Deep_Learning\NLP\Task1\tag1.csv")
df.drop(columns="Unnamed: 0",inplace=True)

In [16]:
df

,content,keywords
0,"""La Cour constitutionnelle,composC)e des prC)s...",Vernietigingsbevoegdheid (Grondwettelijk Hof)
1,"""Het Grondwettelijk Hof,samengesteld uit de vo...",Vernietigingsbevoegdheid (Grondwettelijk Hof)
2,"""Der Verfassungsgerichtshof,zusammengesetzt au...",Vernietigingsbevoegdheid (Grondwettelijk Hof)
3,"""La Cour constitutionnelle,composC)e des prC)s...",Vernietigingsbevoegdheid (Grondwettelijk Hof)
4,"""Het Grondwettelijk Hof,samengesteld uit de vo...",Vernietigingsbevoegdheid (Grondwettelijk Hof)
...,...,...
752,"""Het Grondwettelijk Hof,samengesteld uit de vo...",Prejudiciële bevoegheid (Grondwettelijk Hof)
753,"""Het Grondwettelijk Hof,samengesteld uit de vo...",Prejudiciële bevoegheid (Grondwettelijk Hof)
754,"""Der Verfassungsgerichtshof,zusammengesetzt au...",Prejudiciële bevoegheid (Grondwettelijk Hof)
755,"""Klagen auf vC6llige oder teilweise Nichtigerk...",Prejudiciële bevoegheid (Grondwettelijk Hof)
756,"""Het Grondwettelijk Hof,samengesteld uit de vo...",Prejudiciële bevoegheid (Grondwettelijk Hof)

In [4]:
from langdetect import detect

df["language"] = df["content"].apply(detect)

In [5]:
df

,content,keywords,language
0,"""La Cour constitutionnelle,composC)e des prC)s...",Vernietigingsbevoegdheid (Grondwettelijk Hof),fr
1,"""Het Grondwettelijk Hof,samengesteld uit de vo...",Vernietigingsbevoegdheid (Grondwettelijk Hof),nl
2,"""Der Verfassungsgerichtshof,zusammengesetzt au...",Vernietigingsbevoegdheid (Grondwettelijk Hof),de
3,"""La Cour constitutionnelle,composC)e des prC)s...",Vernietigingsbevoegdheid (Grondwettelijk Hof),fr
4,"""Het Grondwettelijk Hof,samengesteld uit de vo...",Vernietigingsbevoegdheid (Grondwettelijk Hof),nl
...,...,...,...
752,"""Het Grondwettelijk Hof,samengesteld uit de vo...",Prejudiciële bevoegheid (Grondwettelijk Hof),nl
753,"""Het Grondwettelijk Hof,samengesteld uit de vo...",Prejudiciële bevoegheid (Grondwettelijk Hof),nl
754,"""Der Verfassungsgerichtshof,zusammengesetzt au...",Prejudiciële bevoegheid (Grondwettelijk Hof),de
755,"""Klagen auf vC6llige oder teilweise Nichtigerk...",Prejudiciële bevoegheid (Grondwettelijk Hof),de
756,"""Het Grondwettelijk Hof,samengesteld uit de vo...",Prejudiciële bevoegheid (Grondwettelijk Hof),nl

In [6]:
df["language"].value_counts()

language
nl    309
fr    235
de    212
bn      1
Name: count, dtype: int64

In [8]:
import langid

df["language_langid"] = df["content"].apply(lambda x: langid.classify(x)[0])

In [10]:
df["language_langid"].value_counts()

language_langid
nl    310
fr    232
de    214
zh      1
Name: count, dtype: int64

In [12]:
# import spacy
# from spacy_langdetect import LanguageDetector

# nlp = spacy.load("en_core_web_sm")
# nlp.add_pipe("language_detector", last=True)

# def detect_lang(text):
#     doc = nlp(text)
#     return doc._.language["language"]

# df["language_spacy"] = df["content"].apply(detect_lang)

In [31]:

# from lingua import Language, LanguageDetectorBuilder
# detector = LanguageDetectorBuilder.from_all_languages().build()

from lingua import Language, LanguageDetectorBuilder
detector = LanguageDetectorBuilder.from_languages(
    Language.FRENCH, Language.DUTCH, Language.GERMAN
).build()

In [32]:
df["lang_lingua1"] = df["content"].apply(
    lambda text: (
        detector.detect_language_of(text).iso_code_639_1.name
        if isinstance(text, str)
        else None
    )
)

In [34]:
df[df["lang_lingua"]=="YO"]["content"]

83    \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
Name: content, dtype: str

In [30]:
df["lang_lingua"].value_counts()

lang_lingua
NL    308
FR    228
DE    220
YO      1
Name: count, dtype: int64

In [33]:
df["lang_lingua1"].value_counts()

lang_lingua1
NL    308
FR    228
DE    221
Name: count, dtype: int64